const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.ethereal.email',
  port: process.env.SMTP_PORT || 587,
  auth: {
    user: process.env.SMTP_USER || 'ethereal.user@example.com',
    pass: process.env.SMTP_PASS || 'ethereal.pass',
  },
});

const sendOTP = async (email, code) => {
  const mailOptions = {
    from: '"ExamFlow Security" <noreply@examflow.com>',
    to: email,
    subject: 'Verification Required: Official Access Code',
    text: `Your official access code is: ${code}. Do not share this identity key.`,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #0f172a; color: white; padding: 40px; text-align: center; border-radius: 20px;">
        <h1 style="color: #6366f1; text-transform: uppercase; letter-spacing: 5px;">Identity Check</h1>
        <p style="color: #94a3b8; font-size: 14px;">ENTER THE FOLLOWING ACCESS KEY TO ACTIVATE YOUR PROFILE</p>
        <div style="background-color: #1e293b; padding: 20px; border-radius: 10px; margin: 30px auto; width: fit-content; border: 1px solid #334155;">
          <span style="font-size: 32px; font-weight: 900; letter-spacing: 12px; color: white;">${code}</span>
        </div>
        <p style="color: #475569; font-size: 10px; text-transform: uppercase;">Generated by ExamFlow v4.0.2 - Protected Session</p>
      </div>
    `,
  };

  try {
    console.log(`📡 Attempting delivery to ${email} via ${process.env.SMTP_USER || 'DEFAULT'}...`);
    const info = await transporter.sendMail(mailOptions);
    console.log(`✅ Success: Official Key [${code}] dispatched. (ID: ${info.messageId})`);
    return true;
  } catch (err) {
    console.error('❌ CRITICAL MAIL FAILURE:', err.message);
    console.log(`[DEBUG] Identity Key for ${email} is: ${code} (Manual Entry Authorized)`);
    return false;
  }
};


module.exports = { sendOTP };
